### ISSUE TITLE
Add change log 

### ISSUE THREAD

**Issue by DinuNuggets** [veigamann/sydney-whatsapp-chatbot#10]
You should add a changelog where you document which features, bugs etc. have been added.

**Comment by DinuNuggets** [comment]
I just noticed that there is a changelog in GitHub (Even if this one is confusing)

**Comment by veigamann** [comment]
This is a great idea. I'm new to Github, so I'm still learning how to manage a repo. I'll keep this in mind for future updates. Also, i think we need a public roadmap.
