### ISSUE TITLE
Sydney not working anymore because of captcha needs to be solved

### ISSUE THREAD

**Issue by spymaster2O** [veigamann/sydney-whatsapp-chatbot#117]
This is what i am getting when trying to ask sydney something.
[object Object]: CaptchaChallenge: User needs to solve CAPTCHA to continue.
{
  error: {
    name: 'Error',
    message: 'CaptchaChallenge: User needs to solve CAPTCHA to continue.',
    stack: 'Error: CaptchaChallenge: User needs to solve CAPTCHA to continue.\n' +
      '    at WebSocket.<anonymous> (file:///E:/whatsapp-sydney-chatbot/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:493:36)\n' +
      '    at WebSocket.emit (node:events:525:35)\n' +
      '    at WebSocket.emit (node:domain:489:12)\n' +
      '    at Receiver.receiverOnMessage (E:\\whatsapp-sydney-chatbot\\node_modules\\ws\\lib\\websocket.js:1184:20)\n' +
      '    at Receiver.emit (node:events:513:28)\n' +
      '    at Receiver.emit (node:domain:489:12)\n' +
      '    at Receiver.dataMessage (E:\\whatsapp-sydney-chatbot\\node_modules\\ws\\lib\\receiver.js:541:14)\n' +
      '    at Receiver.getData (E:\\whatsapp-sydney-chatbot\\node_modules\\ws\\lib\\receiver.js:459:17)\n' +
      '    at Receiver.startLoop (E:\\whatsapp-sydney-chatbot\\node_modules\\ws\\lib\\receiver.js:158:22)\n' +
      '    at Receiver._write (E:\\whatsapp-sydney-chatbot\\node_modules\\ws\\lib\\receiver.js:84:10)\n' +
      '    at writeOrBuffer (node:internal/streams/writable:392:12)\n' +
      '    at _write (node:internal/streams/writable:333:10)\n' +
      '    at Receiver.Writable.write (node:internal/streams/writable:337:10)\n' +
      '    at TLSSocket.socketOnData (E:\\whatsapp-sydney-chatbot\\node_modules\\ws\\lib\\websocket.js:1278:35)\n' +
      '    at TLSSocket.emit (node:events:513:28)\n' +
      '    at TLSSocket.emit (node:domain:489:12)'
  }
}

**Comment by Luisotee** [comment]
Open bingchat in your desktop and solve the captcha there.

**Comment by DinuNuggets** [comment]
The bingai does not appear on my server's ip

![Screenshot 2023-07-23 002013](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/61915816/2e426add-3273-47c8-b29b-6aadee593503)
![Screenshot 2023-07-23 001913](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/61915816/f3afe134-580a-4912-8623-15893babdd51)

**Comment by DinuNuggets** [comment]
Update: The Bing AI button suddenly started to exist again

**Comment by solution01** [comment]
I didn't find where there is this CAPTCHA could you give more details? @Luisotee

**Comment by Luisotee** [comment]
> I didn't find where there is this CAPTCHA could you give more details? @Luisotee

Send a message to bingchat in the same account that you use the token

https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx
