### ISSUE TITLE
Add generate images

### ISSUE THREAD

**Issue by DinuNuggets** [veigamann/sydney-whatsapp-chatbot#12]
The Bing AI can also generate images. is it possible to add this to the whatsapp bot too?

**Comment by veigamann** [comment]
I'm unsure if [waylaidwanderer/node-chatgpt-api](https://github.com/waylaidwanderer/node-chatgpt-api/) currently supports this functionality, but we could explore alternative methods for generating images, such as utilizing DALL-E. However, I believe this is a low-priority task at the moment.

**Comment by Luisotee** [comment]
[waylaidwanderer/node-chatgpt-api](https://github.com/waylaidwanderer/node-chatgpt-api/) supports it as of v1.37.0.
