### ISSUE TITLE
Sydney can't log into Whatsapp Web

### ISSUE THREAD

**Issue by Ryzitos** [veigamann/sydney-whatsapp-chatbot#149]
Well, since yesterday afternoon I've been trying to connect Sydney to my whatsapp and I haven't been successful in any of the times. Tried to reinstall multiple times, changed bing cookie multiple times too and nothing changed.
Basically it doesn't show any apparent error, but it keeps trying to connect forever in the terminal. 

I'll leave here the steps to try to reproduce this problem, although I'm still not sure if it's something personal or global: 

1- Download and install Sydney as per the steps in this repository 
2- Scan the qr code that will appear
3- Wait to see if Sydney can make it past the "Logging in..." 

![Screenshot_20230825-134054_Termux.png](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/132636475/e1085219-089b-40fc-bdf2-2e3b51677800)

Thank you for your attention and sorry for the excessive issues I've been doing recently.

**Comment by Luisotee** [comment]
I am also suffering from this, will try to see what is wrong later

**Comment by Ryzitos** [comment]
> I am also suffering from this, will try to see what is wrong later

Ok thanks a lot sir 👍✨

**Comment by Luisotee** [comment]
Fixed in #150. Problem was with whatsapp web js, you need to git pull and yarn install.

**Comment by gaborvecsei** [comment]
Unfortunately, this problem still exists
