### ISSUE TITLE
Error asking sydney questions

### ISSUE THREAD

**Issue by solution01** [veigamann/sydney-whatsapp-chatbot#152]
Every time I ask Sydney questions I get this error in the console:

error: {
    name: 'Success',
    message: 'null',
    stack: 'Success: null\n' +
      '    at BingAIClient.sendMessage (file:///sydney-whatsapp-chatbot/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:229:31)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'

**Comment by Luisotee** [comment]
Fixed in latest commit
