### ISSUE TITLE
Sydney doesn't respond

### ISSUE THREAD

**Issue by Ryzitos** [veigamann/sydney-whatsapp-chatbot#153]
Either Sydney has a captcha error, or it is unresponsive, in addition to adding the gear reaction to new messages even without answering the previous one, I had to send several messages until he reacted with the arrows indicating that he is busy answering another one.

But he managed to connect with whatsapp normally now 

After these unanswered buggy messages, it presented an error and crashed: 
```
file:///root/sydney-whatsapp-chatbot/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:493
                            reject(new Error(`${event.item.result.value}: ${event.item.result.message}`));
                                   ^
Error: CaptchaChallenge: User needs to solve CAPTCHA to continue.
    at WebSocket.<anonymous> (file:///root/sydney-whatsapp-chatbot/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:493:36)
    at WebSocket.emit (node:events:525:35)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.emit (node:domain:489:12)
    at Receiver.dataMessage (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/receiver.js:541:14)
    at Receiver.getData (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/receiver.js:459:17)
    at Receiver.startLoop (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/receiver.js:158:22)
    at Receiver._write (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Receiver.Writable.write (node:internal/streams/writable:336:10)
    at TLSSocket.socketOnData (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/websocket.js:1278:35)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[nodemon] app crashed - waiting for file changes before starting...

```
    

![Screenshot_20230826-065204_WhatsApp.png](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/132636475/ea537a54-ce13-4d34-bd1e-a2c59a5b23c1)

also I also tried a clean install and it didn't work. I'll try to install it on another device and if I'm successful I'll come back here to let you know

**Comment by Luisotee** [comment]
Você já fez o captcha no chat do bing? Se não é só fazer, igual fala no #117

**Comment by veigamann** [comment]
@Ryzitos abra o Bing Chat no Edge (esteja logado na sua conta), mande qualquer mensagem e faça a verificação do captcha. Depois disso troque o cookie do .env pelo cookie dessa sessão nova do Edge. Preencha o campo BING_COOKIES conforme é ensinado no readme. Não recomendo preencher o BING_TOKEN.

**Comment by Ryzitos** [comment]
> @Ryzitos abra o Bing Chat no Edge (esteja logado na sua conta), mande qualquer mensagem e faça a verificação do captcha. Depois disso troque o cookie do .env pelo cookie dessa sessão nova do Edge. Preencha o campo BING_COOKIES conforme é ensinado no readme. Não recomendo preencher o BING_TOKEN.

okie, thx thank you both for mentioning this. I didn't know I had to do a captcha in the session 🐢

**Comment by Ryzitos** [comment]
> Você já fez o captcha no chat do bing? Se não é só fazer, igual fala no #117 

I hadn't, thanks for letting me know!

**Comment by Ryzitos** [comment]
Fiz exatamente como mencionado e ele continuou dando falha de captcha, o que será que pode ser?

passos que segui:
1- Abrir Microsoft Edge
2- Logar na conta Microsoft da qual uso o Bing
3- Abrir o chat na aba de pesquisa
4- enviar qualquer mensagem a ele, aguardar resposta e após isso pegar o _U Cookie da sessão.

Após isso ele continuou dando erro de captcha no WhatsApp, embora funcione normalmente no Edge.

Suspeito que seja meu dispositivo, mas ainda não tive tempo de testar em outro, então vou deixar em aberto para caso haja outra solução! Desde já agradeço.

**Comment by veigamann** [comment]
Notei que você falou em português com o bot, vamos decidir uma língua pra se comunicar. Você é brasileiro?

Tenta de novo, mas dessa vez sem cookies. Deixe os campos BING_TOKEN e BING_COOKIE como uma string vazia, só com aspas. Deve funcionar. Se der erro, me avisa

**Comment by Ryzitos** [comment]
> Notei que você falou em português com o bot, vamos decidir uma língua pra se comunicar. Você é brasileiro?
> 
> Tenta de novo, mas dessa vez sem cookies. Deixe os campos BING_TOKEN e BING_COOKIE como uma string vazia, só com aspas. Deve funcionar. Se der erro, me avisa

Ok vou tentar, estou apenas reinstalando tudo para ter certeza que não é algo corrompido de minha parte!

E sim sou brasileiro, mudei de linguaguem algumas vezes com o bot pra ver se ele respondia

**Comment by Ryzitos** [comment]
> Notei que você falou em português com o bot, vamos decidir uma língua pra se comunicar. Você é brasileiro?
> 
> Tenta de novo, mas dessa vez sem cookies. Deixe os campos BING_TOKEN e BING_COOKIE como uma string vazia, só com aspas. Deve funcionar. Se der erro, me avisa


Primeiro testei colocar o cookie de uma outra conta: entrei no Bing Chat, mandei uma mensagem e logo após coletei o _U da sessão e coloquei no Sydney após a reinstalação limpa. Mesmo assim ele continuou apresentando erro de captcha,

logo após removi o cookie e deixei apenas "" (removi o BING_COOKIE e o BING_TOKEN e deixei apenas as aspas) e também apresentou erro de captcha. Estou muito confuso...

![Screenshot_20230826-150207_YoWhatsApp.png](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/132636475/979c4f27-c633-4a70-817b-381cd0e5a895)

----------------------------------------------------------------------

Erro antes de remover os cookies e o token:
error: {
```
    name: 'Error',
    message: 'CaptchaChallenge: User needs to solve CAPTCHA to continue.',
    stack: 'Error: CaptchaChallenge: User needs to solve CAPTCHA to continue.\n' +
      '    at WebSocket.<anonymous> (file:///root/sydney-whatsapp-chatbot/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:493:36)\n' +
      '    at WebSocket.emit (node:events:525:35)\n' +
      '    at WebSocket.emit (node:domain:489:12)\n' +
      '    at Receiver.receiverOnMessage (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/websocket.js:1184:20)\n' +
      '    at Receiver.emit (node:events:513:28)\n' +
      '    at Receiver.emit (node:domain:489:12)\n' +
      '    at Receiver.dataMessage (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/receiver.js:541:14)\n' +
      '    at Receiver.getData (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/receiver.js:459:17)\n' +
      '    at Receiver.startLoop (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/receiver.js:158:22)\n' +
      '    at Receiver._write (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/receiver.js:84:10)\n' +
      '    at writeOrBuffer (node:internal/streams/writable:391:12)\n' +
      '    at _write (node:internal/streams/writable:332:10)\n' +
      '    at Receiver.Writable.write (node:internal/streams/writable:336:10)\n' +
      '    at TLSSocket.socketOnData (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/websocket.js:1278:35)\n' +
      '    at TLSSocket.emit (node:events:513:28)\n' +
      '    at TLSSocket.emit (node:domain:489:12)'
  }
```

--------------------------|


Erro após remover os cookies e o token, deixando apenas as aspas (""):
```
error: {
    name: 'Error',
    message: 'CaptchaChallenge: User needs to solve CAPTCHA to continue.',
    stack: 'Error: CaptchaChallenge: User needs to solve CAPTCHA to continue.\n' +
      '    at WebSocket.<anonymous> (file:///root/sydney-whatsapp-chatbot/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:493:36)\n' +
      '    at WebSocket.emit (node:events:525:35)\n' +
      '    at WebSocket.emit (node:domain:489:12)\n' +
      '    at Receiver.receiverOnMessage (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/websocket.js:1184:20)\n' +
      '    at Receiver.emit (node:events:513:28)\n' +
      '    at Receiver.emit (node:domain:489:12)\n' +
      '    at Receiver.dataMessage (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/receiver.js:541:14)\n' +
      '    at Receiver.getData (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/receiver.js:459:17)\n' +
      '    at Receiver.startLoop (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/receiver.js:158:22)\n' +
      '    at Receiver._write (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/receiver.js:84:10)\n' +
      '    at writeOrBuffer (node:internal/streams/writable:391:12)\n' +
      '    at _write (node:internal/streams/writable:332:10)\n' +
      '    at Receiver.Writable.write (node:internal/streams/writable:336:10)\n' +
      '    at TLSSocket.socketOnData (/root/sydney-whatsapp-chatbot/node_modules/ws/lib/websocket.js:1278:35)\n' +
      '    at TLSSocket.emit (node:events:513:28)\n' +
      '    at TLSSocket.emit (node:domain:489:12)'
  }
```

----------------------------------------------------------------------

**Comment by veigamann** [comment]
Fica em paz kkkk tudo certo 👍🏻
