### ISSUE TITLE
Sydney bugged after remembering too much lmao

### ISSUE THREAD

**Issue by Ryzitos** [veigamann/sydney-whatsapp-chatbot#154]
It works great in general, however I've noticed that for some reason if you ask him for something, he never forgets what you asked for and always includes your request in his next messages. In summary he begins to accumulate orders to the point that the message becomes unreadable 
Like, you don't have to ask him to remember, or ask him to keep putting it in every message, if you ask him for example: "Do you like coffee Sydney?" he will start including that he likes coffee and a description of it in every subsequent message. And that goes for anything. 

It's funny to see this, me and my friends laugh a lot but it ends up getting in the way after a while, because he just doesn't answer questions anymore because his messages are full of old requests. !reset usually solves it but I don't always have the admin to use it, and believing that this is a bug I thought it best to report it

![Screenshot_20230827-112455_WhatsApp.png](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/132636475/fb0d3935-9050-4f33-aa57-5de84b4f79c7)

![Screenshot_20230826-210526_WhatsApp.png](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/132636475/824e1ec0-8ab6-43f6-ba09-816e215af488)

![Screenshot_20230827-105137_WhatsApp.png](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/132636475/6b361bfc-112f-4100-8bdf-2536a90b10cb)

To reproduce the bug is very simple:
1- Start the bot and ask for something, note that it will include your request in all future messages

**Comment by Luisotee** [comment]
Did you update node-chatgpt-api beyond 1.37.0?

**Comment by Ryzitos** [comment]
> Did you update node-chatgpt-api beyond 1.37.0?

Well I did a clean install of Sydney, I must be up to date right? I'm quite layman

**Comment by Luisotee** [comment]
This usually happens in the newest node-chatgpt-api (1.37.1 to 1.37.3) because there is a problem on how we implemented the api ( The error is probably on our side). Try to do a `yarn upgrade @waylaidwanderer/chatgpt-api@v1.37.0`

**Comment by Ryzitos** [comment]
> This usually happens in the newest node-chatgpt-api (1.37.1 to 1.37.3) because there is a problem on how we implemented the api ( The error is probably on our side). Try to do a `yarn upgrade @waylaidwanderer/chatgpt-api@v1.37.0`

got it, I am going to try

**Comment by Ryzitos** [comment]
> This usually happens in the newest node-chatgpt-api (1.37.1 to 1.37.3) because there is a problem on how we implemented the api ( The error is probably on our side). Try to do a `yarn upgrade @waylaidwanderer/chatgpt-api@v1.37.0`

it worked perfectly, now sydney is not accumulating answers! thank you so much ♥️♥️

![Screenshot_20230827-200735_WhatsApp.png](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/132636475/d4f90c56-9180-42e7-ac67-54b1ccfb8a53)

**Comment by Ryzitos** [comment]
> This usually happens in the newest node-chatgpt-api (1.37.1 to 1.37.3) because there is a problem on how we implemented the api ( The error is probably on our side). Try to do a `yarn upgrade @waylaidwanderer/chatgpt-api@v1.37.0`

Just in closing I wanted to ask you, is there any command like this you mentioned to fix the issue that installs the node-api Jailbreak patch for Sydney? last time i had to download the file and manually insert it into the sydney files

**Comment by Ryzitos** [comment]
> This usually happens in the newest node-chatgpt-api (1.37.1 to 1.37.3) because there is a problem on how we implemented the api ( The error is probably on our side). Try to do a `yarn upgrade @waylaidwanderer/chatgpt-api@v1.37.0`

Just in closing I wanted to ask you, is there any command like this you mentioned to fix the issue that installs the node-api Jailbreak patch for Sydney? last time i had to download the file and manually insert it into the sydney files

**Comment by Luisotee** [comment]
The patch that fixed it is the 1.37.3, and it has that problem that you just mentioned so right now the only fix is to manually adding the changes that [that](https://github.com/waylaidwanderer/node-chatgpt-api/commit/44f5aeda49223d1079134cd30cb25daf2361416e) commit made. 

If you replace the entire file the problem of this issue will appear.

**Comment by Ryzitos** [comment]
> The patch that fixed it is the 1.37.3, and it has that problem that you just mentioned so right now the only fix is to manually adding the changes that [that](https://github.com/waylaidwanderer/node-chatgpt-api/commit/44f5aeda49223d1079134cd30cb25daf2361416e) commit made. 
> 
> If you replace the entire file the problem of this issue will appear.

I understand thank you very much 👍✨

**Comment by Luisotee** [comment]
@Ryzitos #155 should fix among others things the jailbreak and the problem of this issue.

**Comment by Ryzitos** [comment]
> @Ryzitos #155 should fix among others things the jailbreak and the problem of this issue.
> 
> Just update or do a clean install and should be ready to go

okie thx 👍, Before, I had managed to mess with the three lines of code in the commit, but it took me 30 minutes because I was afraid of making it completely buggy lol

**Comment by Ryzitos** [comment]
> @Ryzitos #155 should fix among others things the jailbreak and the problem of this issue.
> 
> Just update or do a clean install and should be ready to go

Just coming back to let you know that I've updated and it's working perfectly, thank you so much for taking the time to resolve these issues. I really appreciate it 🙏
