### ISSUE TITLE
There is no time out when there used to be.

### ISSUE THREAD

**Issue by Abdalnablse10** [veigamann/sydney-whatsapp-chatbot#172]
It used to be that sometimes when Sydney is not responding it will time out, but now there is no longer a time out and the bot will keep "typing" for hours until i restart it.

**Comment by solution01** [comment]
It happens to me too from time to time

**Comment by Luisotee** [comment]
Is this still happening? It's working fine for me

![image](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/50471205/ee624dee-ac9f-49c5-9464-83ed05a04d34)
