### ISSUE TITLE
Group chat capabilities

### ISSUE THREAD

**Issue by veigamann** [veigamann/sydney-whatsapp-chatbot#20]
Currently, Sydney lacks awareness of being in a group chat and mistakenly assumes all messages are from a single person. To improve this, the following implementation can be adopted:

1. Check each received message to determine if it belongs to a group or a private chat.
2. If it is a group chat, Sydney should only respond if it is specifically mentioned (e.g., "@Sydney, what time is it?") or if Sydney's previous message was replied to within a thread (AKA the reply functionality in WhatsApp where messages can be threaded).
3. Sydney should also be aware of the name of the participant who mentioned it, enabling a coherent conversation.

This approach provides a more semantic and intuitive way to refer to the bot whenever you want a response.

Note: Sydney will not actively read every single message in the group to learn about its context, as this is slow and leads to unpredictable behavior.

**Comment by veigamann** [comment]
This originated from #6. Thanks, @Ryzitos!

**Comment by Ryzitos** [comment]
> This originated from #6. Thanks, @Ryzitos!

OMG I THANK YOU, you are literally the best creator on this platform that I have ever been able to talk to and solve my problems, thank you so much ✨✨✨💪💪

**Comment by Ryzitos** [comment]
Sorry for the question, I'm very new to the GitHub structure in general, but this is a feature that will be implemented, right? (I got confused and thought it had already been released)

**Comment by Ryzitos** [comment]
Sorry for the question, I'm very new to the GitHub structure in general, but this is a feature that will be implemented, right? (I got confused and thought it had already been released)

**Comment by veigamann** [comment]
Added in 55b92eb.
