### ISSUE TITLE
Pick between different LLMs

### ISSUE THREAD

**Issue by veigamann** [veigamann/sydney-whatsapp-chatbot#21]
Provide the capability to choose from a range of LLM models, including:

- GPT3.5
- GPT4
- Other open source models like Vicuna and variations

**Comment by Luisotee** [comment]
The user should be able to switch between different AI modes within WhatsApp using a command like '!changeAI'

**Comment by veigamann** [comment]
After spending some time thinking on this, I think it's important to remember that each language model is individually fine-tuned and behaves differently. Currently, our implemented features only account for Bing/Sydney. However, managing conversations with other language models, particularly open-source/smaller models or those not based on GPT, presents a completely different scenario. Therefore, it might be necessary to abandon the idea altogether, as it doesn't align with the medium (WhatsApp) we intend to use for these model conversations. WhatsApp conversations are linear, they follow a single line of thought. Mixing different conversations threads in a single chat is a bad idea. We can still offer multiple models for selection, but this implies in more workforce. Users should only choose a model when first initializing the bot or when starting a specific conversation thread. Changing models in the middle of a conversation should not be allowed.
