### ISSUE TITLE
Sydney should know the name of the users

### ISSUE THREAD

**Issue by DinuNuggets** [veigamann/sydney-whatsapp-chatbot#23]
On WhatsApp, you can choose a public name. Sydney could take this and address the user by name.

**Comment by Luisotee** [comment]
This is already planned in #20

**Comment by DinuNuggets** [comment]
However, it was described as being a feature only for groups

**Comment by Luisotee** [comment]
Oh I thought you meant for groups. If it's with a private chat you can tell Sydney to remember your name, but she might forget it in the long run. You could enforce her to remember your name by putting it in her context, if I have time I will commit a change to make it work through her context, as using the whatsapp name might be a little more complicated than this.

**Comment by Luisotee** [comment]
I added it in a new branch called 'beta.' You can set both your name and Sydney's name through the .env file. Please refer to the .env.example for an example. If you come across any bugs, please let us know!

**Comment by veigamann** [comment]
@Luisotee I think a better approach would be to use WhatsApp's public name as @DinuNuggets mentioned. It could however be optionally overwritten by some `!command`.

**Comment by DinuNuggets** [comment]
My issue is still marked as "closed". I don't think that's still the case and I can't change that

**Comment by Luisotee** [comment]
This issue is marked as closed since the implementation has been completed by PR #24. However, we are planning to change the implementation in the future. This change will be addressed in a separate issue, as it will not only affect the way Sydney remembers the username but also impact several other aspects.
