### ISSUE TITLE
Add multiple accounts

### ISSUE THREAD

**Issue by DinuNuggets** [veigamann/sydney-whatsapp-chatbot#47]
Message from Sydney:
```
Error:

Throttled: Request is throttled.
```

Did I do something wrong? What have I done? does this go away?

**Comment by DinuNuggets** [comment]
I found out that the bot was sending too many messages. 200 is the limit per 24 hours

**Comment by Luisotee** [comment]
Just to be clear to anyone having this issue, the current solution is to either wait for 24 hours or change your `BING_TOKEN` to that of another account which hasn't exceeded the limit. 

For more information click [here](https://github.com/waylaidwanderer/node-chatgpt-api/issues/261).

**Comment by veigamann** [comment]
After some thoughts, I couldn't come up with a solution to add multiple accounts. Closing for now, but feel free to open a discussion so we can (discuss) this and think of an actual method, test and implement it.
