### ISSUE TITLE
Is it possible to display the links that the bot gives in the chat?

### ISSUE THREAD

**Issue by DinuNuggets** [veigamann/sydney-whatsapp-chatbot#5]
If the bot outputs texts as links, they are written in bold in WhatsApp and are not clickable.

**Comment by veigamann** [comment]
This seems like a simple fix. Can you send a screenshot of the bold texts?

**Comment by DinuNuggets** [comment]
![Screenshot 2023-05-17 204835](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/61915816/45571eb2-6154-4ab6-9bbf-3f434aa04f61)

**Comment by veigamann** [comment]
Fixed. For now, Sydney formats stuff with superscripts `([^1^])`, and those are currently being shown as-is. Later I'll see if I can change the system prompt so Sydney replies with a more adequate formatting for WhatsApp rendering (that includes single `*` to bold parts of the message).

![image](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/74165047/9ba2f1fe-9a2c-455a-995c-6248627b4926)

Make sure to update your clone of the project. `git pull` should suffice. Let me know if you have any issue. Closing.
