### ISSUE TITLE
Sydney doesn't respond to every response in groups 

### ISSUE THREAD

**Issue by DinuNuggets** [veigamann/sydney-whatsapp-chatbot#62]
![Screenshot_20230604_094555](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/61915816/033515ea-6a08-4ee4-b840-23381d238b9f)

**Comment by Luisotee** [comment]
Did he reply to the last comment Sydney made? Because it only works if it's the last.

**Comment by DinuNuggets** [comment]
Oh, I didn't know that
