### ISSUE TITLE
Sydney shows this error

### ISSUE THREAD

**Issue by naughtynova69** [veigamann/sydney-whatsapp-chatbot#66]
![Screenshot_2023-06-08-19-51-50-79](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/96471011/852a19e3-493e-447a-8cbb-de2a24b28391)
@veigamann

**Comment by DinuNuggets** [comment]
This is because the public bot was currently having technical difficulties. The public bot is unstable. 
We recommend hosting this yourself

**Comment by veigamann** [comment]
@naughtynova69 Are you self-hosting the bot or are you using the public demo? If you are self-hosting, did you edit `.env` to include `BING_TOKEN`/`BING_COOKIES`?

**Comment by DinuNuggets** [comment]
@veigamann That was probably my mistake with the public bot. A couple of the other accounts didn't work or were misconfigured

**Comment by veigamann** [comment]
Yeah, I understand. Just asking the OP to make sure so we can close the issue properly.

**Comment by naughtynova69** [comment]
It was Public Demo! And also !tone is not working.

**Comment by naughtynova69** [comment]
Now you blocked me. @veigamann
![Screenshot_2023-06-11-11-49-06-59](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/96471011/19b9a46d-97eb-4b39-bf55-eeda97b99aee)

**Comment by DinuNuggets** [comment]
> It was Public Demo! And also !tone is not working.

Tone has been deactivated in the public bot because if you change something there it also applies to other chats for other users



> Now you blocked me. @veigamann ![Screenshot_2023-06-11-11-49-06-59](https://user-images.githubusercontent.com/96471011/244917446-19b9a46d-97eb-4b39-bf55-eeda97b99aee.png)

We didn't block you. The bing AI has a limit of 300 messages per account. Currently, I have to exchange the accounts manually. Please write me an email if you get such a message

**Comment by naughtynova69** [comment]
Sorry!
