### ISSUE TITLE
Remove !reset in groups

### ISSUE THREAD

**Issue by DinuNuggets** [veigamann/sydney-whatsapp-chatbot#67]
There should at least be a solution that no random dude can !reset in groups

**Comment by DinuNuggets** [comment]
Could it check if the person is a group admin when you do !reset?

**Comment by veigamann** [comment]
Related to that, what if we also added a whitelist so the bot only responds (starts new conversations) to certain users? This way you can control who can talk to your bot's self-hosted instance.

**Comment by veigamann** [comment]
> Could it check if the person is a group admin when you do !reset?

Yeah, I think so. After a quick glance in the documentation, I don't see an out-of-the-box solution from `whatsapp-web.js` to check if a user is a group admin, but I think it's not too hard to figure that out.

**Comment by veigamann** [comment]
Implemented in 4079b39

About the whitelist, I'll make a new TODO entry in the roadmap.
