### ISSUE TITLE
Output more descriptive error messages

### ISSUE THREAD

**Issue by DinuNuggets** [veigamann/sydney-whatsapp-chatbot#7]
Sometimes I get this error message from the bot in WhatsApp:
```
Error when answering this message.

Details: {}
```
There is nothing in the console about this

**Comment by veigamann** [comment]
I've also noticed this, which is likely caused by the unresolved or erroring promise sent to Bing. I'll work on fixing it or at least providing a clearer error message to the user.

**Comment by DinuNuggets** [comment]
If that happens, I simply repeat my text until it works. 
Could it be done in a way that the prompt is sent repeatedly automatically until it works?

**Comment by arnab3k** [comment]
Error when answering this message.

Details: {}

I still have not got it to work even once lol

**Comment by veigamann** [comment]
Fixed in 8886f72.
