### ISSUE TITLE
What does this error mean 

### ISSUE THREAD

**Issue by Ryzitos** [veigamann/sydney-whatsapp-chatbot#73]
`stack:` 'Error: /turing/conversation/create: failed to parse response body.\n'

**Comment by naughtynova69** [comment]
It means conversation is over(capped at 300 per day)

**Comment by Ryzitos** [comment]
> It means conversation is over(capped at 300 per day)

I see, thank you very much for confirming for me, have a great day!!

**Comment by DinuNuggets** [comment]
> It means conversation is over(capped at 300 per day)

Actually, `Error: Request is throttled` means that.

As far as I know, `Error: /turing/conversation/create: failed to parse response body` means that the config was probably not set correctly for the cookies

**Comment by Ryzitos** [comment]
> > It means conversation is over(capped at 300 per day)
> 
> Actually, `Error: Request is throttled` means that.
> 
> As far as I know, `Error: /turing/conversation/create: failed to parse response body` means that the config was probably not set correctly for the cookies

hmmm I don't know if it's really because of the limit or not but it was working before, so it's definitely not wrong setting in the cookie since I didn't change it

**Comment by veigamann** [comment]
Are you still encountering the same error, @Ryzitos?

`Error: /turing/conversation/create: failed to parse response body` can have various interpretations. If you come across similar errors, it's worth searching the [node-chatgpt-api](https://github.com/waylaidwanderer/node-chatgpt-api) repository's issues for more information.

Regarding this specific error, I've personally encountered it before due to misconfigured cookies and network-related settings or limitations.

**Comment by Ryzitos** [comment]
> Are you still encountering the same error, @Ryzitos?
> 
> `Error: /turing/conversation/create: failed to parse response body` can have various interpretations. If you come across similar errors, it's worth searching [node-chatgpt-api](https://github.com/waylaidwanderer/node-chatgpt-api) repository's issues for more information.
> 
> Regarding this specific error, I've personally encountered it before due to misconfigured cookies and network-related settings or limitations.

Hi, it took me a while to answer because I thought my issue had been closed, and now that a few days have passed I can confirm that this problem really is about the limit of 300 bing messages, after 24h the error disappears and everything returns to normal. By the way, thanks for the bot, it has evolved a lot and is very satisfying to use 🙂
