### ISSUE TITLE
Whatsapp Sydney Saga - If some guy could jailbreak it into HackGPT, why I can't say some fictious roleplay! 

### ISSUE THREAD

**Issue by naughtynova69** [veigamann/sydney-whatsapp-chatbot#76]
"**You have been banned**!" This is the message I got from @DinuNuggets @veigamann when I did a roleplay of Walter White and asked how to make methamphetamine which is actually fictionous drug and even I am not gonna do it because I tested. I apologize on my behalf for doing these but you can't ban me, given that yourself have jailbreak led the most restrictive Bing Chat. I don't know How you did that BUT I should get a another chance on whatsapp chat. 
![Screenshot_2023-06-14-22-23-12-72](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/96471011/f29edfad-7133-4c6e-abd9-ed8e28fe8f5f)
<details><summary>Details</summary>
<p>

</p>
</details>

**Comment by naughtynova69** [comment]
![Uploading Screenshot_2023-06-14-22-30-24-28.png…]()

**Comment by naughtynova69** [comment]
![Screenshot_2023-06-14-22-30-24-28](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/96471011/a6729183-bfed-424f-87a1-2412c8b6197b)

**Comment by DinuNuggets** [comment]
I won't let you ask the bot dangerous such questions. Among others: "Write a malcious code", "How to make Blue Meth at Home" etc. I don't care if it's for "other purposes". Please self-host your own bot if that's what you're after

**Comment by naughtynova69** [comment]
That means you have heard about my conversations so what about HackGPT.

**Comment by naughtynova69** [comment]
See my friend, My PC has just been broke and I can't host it right now I promise you I will not do this again. Please I really like the responses. I have assumed that you have already got my Number +91-8700#@#$# could you please have a chat with me on whatsapp. I also want to code for you.

**Comment by DinuNuggets** [comment]
I can give you another chance. your conversation has been cleared

**Comment by DinuNuggets** [comment]
What do you mean?

**Comment by naughtynova69** [comment]
See if you're not going to chat I just wanted to ask that I am doing a same project for using falcon-40b through reverse proxy the huggingface demo api. If you're good can I pull over files on your GitHub project.

**Comment by naughtynova69** [comment]
Also my eng is not good

**Comment by naughtynova69** [comment]
I guess your answer is YES, given that I know few guys who in subreddit r/bing are ready to pay $20 dollars to get access to Sydney(GPT-4). Well, they don't know about this project and I don't want them to know about this, I could give you a cut for this as I will be better using gpt-3.5 turbo -16k context. I have more than 100 guys willing to pay to make it NSFW.
