### ISSUE TITLE
Yarn error Command "nodemon" not found.

### ISSUE THREAD

**Issue by putuoka** [veigamann/sydney-whatsapp-chatbot#82]
<img width="447" alt="image" src="https://github.com/veigamann/sydney-whatsapp-chatbot/assets/20880839/f56ffd07-4954-485a-b124-33d4340d811e">

**Comment by veigamann** [comment]
Did you run `yarn install`?

**Comment by putuoka** [comment]
> Did you run `yarn install`?

Yup, I already ran the yarn install and yarn dev commands, and then the error above popped up. 
Anyway  I already fixed the problem with npm install. I didn't use Yarn, and it works now.
