### ISSUE TITLE
Error: CaptchaChallenge: User needs to solve CAPTCHA to continue.

### ISSUE THREAD

**Issue by veigamann** [veigamann/sydney-whatsapp-chatbot#9]
If you ever get this error, check waylaidwanderer/node-chatgpt-api#363

There is a workaround [here](https://github.com/waylaidwanderer/node-chatgpt-api/issues/363#issuecomment-1544965451)

This is outside my scope, can't fix this by myself.

![image](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/74165047/347a9a8a-5f0f-47e0-a45e-7ed223087010)

**Comment by DinuNuggets** [comment]
Since you added the wontfix tag, I recommend ending this issue as "Close as not planned".
