### ISSUE TITLE
How to show QR code in Web Form?

### ISSUE THREAD

**Issue by putuoka** [veigamann/sydney-whatsapp-chatbot#90]
Let say I want to show the QR code in my web. How to do that?

**Comment by Luisotee** [comment]
No idea since we haven't used it in a webpage, but you might have more luck asking in the whatsapp-web-js repo or just looking into google since someone probably has already done this.

**Comment by putuoka** [comment]
> No idea since we haven't used it in a webpage, but you might have more luck asking in the whatsapp-web-js repo or just looking into google since someone probably has already done this.

Hi, guys. how do you keep track of the session/cookie for each DM/chat? I mean, how can it resume from a previous chat, like if I'm asking 'what was the last message I wrote?' The WhatsApp and bot AI seem to know about it. Do you maintain this in your code or it's from sydney code?

**Comment by Luisotee** [comment]
@veigamann is the one who did this and I never bothered to look into it so take this with a grain of salt, but AFAIK we keep it in a sqlite that the program initialize in `src/clients/sydney.ts` 

```
cache: {
    store: new KeyvSqlite({ uri: "sqlite://./conversations_cache.sqlite" })
  }
  ```
  
  This is from the [node-chatgpt-api](https://github.com/waylaidwanderer/node-chatgpt-api).
