### ISSUE TITLE
Voice conversation with Bing Chat

### ISSUE THREAD

**Issue by solution01** [veigamann/sydney-whatsapp-chatbot#97]
Hi guys,

When are we going to have voice chat integrated with bing without the need for the Open AI API?

**Comment by Luisotee** [comment]
Maybe after reminders and pdf reading is done, being optimistic 1-2 weeks.

**Comment by solution01** [comment]
Nice :) Thanks @Luisotee

**Comment by Luisotee** [comment]
Done in #110
